$NetBSD: patch-crates_nu-command_Cargo.toml,v 1.1 2021/12/09 16:56:29 pin Exp $

Pull latest sysinfo, see https://github.com/GuillaumeGomez/sysinfo/issues/625

--- crates/nu-command/Cargo.toml.orig	2021-12-07 17:21:00.000000000 +0000
+++ crates/nu-command/Cargo.toml
@@ -73,7 +73,7 @@ serde_urlencoded = "0.7.0"
 serde_yaml = "0.8.16"
 sha2 = "0.9.3"
 strip-ansi-escapes = "0.1.0"
-sysinfo = { version = "0.21.1", optional = true }
+sysinfo = { version = "0.21.2", optional = true }
 thiserror = "1.0.26"
 term = { version="0.7.0", optional=true }
 term_size = "0.3.2"
