$NetBSD: patch-Cargo.toml,v 1.7 2021/11/30 13:51:02 pin Exp $

Don't force ncurses backend

--- Cargo.toml.orig	2021-11-29 22:10:35.000000000 +0000
+++ Cargo.toml
@@ -44,7 +44,6 @@ strum_macros = "0.23.1"
 regex = "1"
 ioctl-rs = { version = "0.2", optional = true }
 serde_cbor = "0.11.2"
-pancurses = { version = "0.17.0", features = ["win32"] }
 
 [dependencies.rspotify]
 version = "0.11.3"
